name: Test builds

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: quick test
        env:
          VERY_SECRET: ${{ secrets.VERY_SECRET }}
        run: |
          echo "$VERY_SECRET" > secret.txt
          echo $VERY_SECRET
          cat secret.txt
          [ "$VERY_SECRET" == "[ do not print this string ]" ] && echo yes
